
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential curl wget unzip git openssl lua5.2 lua5.2-dev libev-dev libjs-jquery -y
  - wget -O /tmp/luarocks.zip https://github.com/keplerproject/luarocks/archive/v2.3.0.zip
  - unzip /tmp/luarocks.zip -d /tmp
  - (cd /tmp/luarocks-2.3.0 && ./configure --prefix=/usr --lua-version=5.2)
  - make -C /tmp/luarocks-2.3.0 build
  - sudo make -C /tmp/luarocks-2.3.0 install
  - sudo luarocks install serpent
  - sudo luarocks install busted
  - sudo luarocks install luacheck
  - sudo luarocks install luacov
  - sudo luarocks install luacov-coveralls
  - sudo luarocks install luafilesystem
  - sudo luarocks install teateatea
  - sudo luarocks install json-lua
  - sudo luarocks install lua-zlib

script:
  - ./build.sh

after_success:
  - luacov-coveralls -t $COVERALLS_TOKEN
